CXX = g++
CFLAGS = -Wall -Wextra -pedantic -std=c++11
OBJECTS_PART1 = day2_part1.cpp
OBJECTS_PART2 = day2_part2.cpp
OUTPUT_PART1 = day2_1
OUTPUT_PART2 = day2_2

part1:
	$(CXX) $(OBJECTS_PART1) $(CFLAGS) -o $(OUTPUT_PART1)

part2:
	$(CXX) $(OBJECTS_PART2) $(CFLAGS) -o $(OUTPUT_PART2)

clean:
	rm -f $(OUTPUT_PART1) $(OUTPUT_PART2)
